"""High level controller that interprets chat requests and orchestrates builds."""
from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import Dict, List

from .build_stream import build_stream
from .code_executor import ExecutionContext, code_executor
from .project_manager import project_manager
from .utils import slugify


@dataclass
class BuildStep:
    title: str
    description: str
    files: Dict[str, str]
    explanation: str

    def to_dict(self) -> Dict[str, str]:
        return {
            "title": self.title,
            "description": self.description,
            "explanation": self.explanation,
            "files": list(self.files.keys()),
        }


@dataclass
class BuildPlan:
    name: str
    summary: str
    stack: str
    steps: List[BuildStep]

    def to_dict(self) -> Dict[str, object]:
        return {
            "name": self.name,
            "summary": self.summary,
            "stack": self.stack,
            "steps": [step.to_dict() for step in self.steps],
        }


class AIController:
    """Interpret prompts and drive the building workflow."""

    def create_plan(self, prompt: str) -> BuildPlan:
        prompt_lower = prompt.lower()
        if any(keyword in prompt_lower for keyword in ("api", "backend", "endpoint", "service")):
            return self._plan_backend(prompt)
        if any(keyword in prompt_lower for keyword in ("website", "landing", "page", "ui", "interface")):
            return self._plan_website(prompt)
        if any(keyword in prompt_lower for keyword in ("model", "train", "machine learning")):
            return self._plan_ml(prompt)
        return self._plan_script(prompt)

    # ------------------------------------------------------------------
    # plan templates
    # ------------------------------------------------------------------
    def _plan_website(self, prompt: str) -> BuildPlan:
        name = slugify(prompt) or "ai-website"
        summary = f"Interactive website generated for: {prompt.strip()}"
        steps: List[BuildStep] = [
            BuildStep(
                title="Project overview",
                description="Draft the README describing goals and stack.",
                explanation="Documentation keeps each generated project understandable.",
                files={
                    "README.md": (
                        f"# {prompt.strip().title()}\n\n"
                        "This project was generated by AI-WebForge's live builder."
                        "\n\nIt delivers a responsive landing page tailored to your brief."
                        "\n\n## Getting started\n\nOpen `index.html` in a browser or serve the `public` folder."
                    ),
                },
            ),
            BuildStep(
                title="Create the HTML shell",
                description="Set up a semantic layout with hero, features, and CTA sections.",
                explanation="The structure follows modern landing page patterns for clarity.",
                files={
                    "public/index.html": (
                        "<!DOCTYPE html>\n"
                        "<html lang=\"en\">\n"
                        "  <head>\n"
                        "    <meta charset=\"UTF-8\" />\n"
                        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                        "    <title>AI Builder — {title}</title>\n"
                        "    <link rel=\"stylesheet\" href=\"./styles.css\" />\n"
                        "  </head>\n"
                        "  <body>\n"
                        "    <div class=\"page\">\n"
                        "      <header class=\"hero\">\n"
                        "        <div class=\"badge\">Live AI Build</div>\n"
                        "        <h1>{heading}</h1>\n"
                        "        <p>{subheading}</p>\n"
                        "        <div class=\"cta\">\n"
                        "          <a class=\"button primary\" href=\"#request\">Start a project</a>\n"
                        "          <a class=\"button ghost\" href=\"#features\">See how it works</a>\n"
                        "        </div>\n"
                        "      </header>\n"
                        "      <section id=\"features\" class=\"panel\">\n"
                        "        <h2>Why this build is unique</h2>\n"
                        "        <div class=\"grid\">\n"
                        "          <article>\n"
                        "            <h3>Live reasoning</h3>\n"
                        "            <p>The AI explains each decision and streams progress in real time.</p>\n"
                        "          </article>\n"
                        "          <article>\n"
                        "            <h3>Full control</h3>\n"
                        "            <p>Jump into any generated file, edit it, and run the project instantly.</p>\n"
                        "          </article>\n"
                        "          <article>\n"
                        "            <h3>Reusable projects</h3>\n"
                        "            <p>Every build is saved so you can iterate, fork, or export without friction.</p>\n"
                        "          </article>\n"
                        "        </div>\n"
                        "      </section>\n"
                        "      <section id=\"request\" class=\"panel dark\">\n"
                        "        <h2>Ready for the next idea?</h2>\n"
                        "        <p>Describe what you want and the AI Builder will assemble it while you watch.</p>\n"
                        "        <form class=\"request-form\">\n"
                        "          <label for=\"email\">Stay in the loop</label>\n"
                        "          <div class=\"request-form__row\">\n"
                        "            <input id=\"email\" type=\"email\" placeholder=\"you@example.com\" required />\n"
                        "            <button type=\"submit\">Notify me</button>\n"
                        "          </div>\n"
                        "        </form>\n"
                        "      </section>\n"
                        "      <footer class=\"footer\">\n"
                        "        <p>Generated live by AI-WebForge.</p>\n"
                        "      </footer>\n"
                        "    </div>\n"
                        "    <script src=\"./app.js\"></script>\n"
                        "  </body>\n"
                        "</html>\n"
                    ).format(
                        title=prompt.strip(),
                        heading=prompt.strip().title(),
                        subheading="Watch an AI developer design and code alongside you.",
                    ),
                },
            ),
            BuildStep(
                title="Add styling and motion",
                description="Craft the gradient aesthetic and interactive hover states.",
                explanation="A consistent visual system reinforces the futuristic builder persona.",
                files={
                    "public/styles.css": (
                        ":root {\n"
                        "  color-scheme: dark;\n"
                        "  font-family: 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n"
                        "  background: radial-gradient(circle at top, #0f172a, #020617 65%);\n"
                        "  color: #f8fafc;\n"
                        "}\n\n"
                        "body {\n  margin: 0;\n  min-height: 100vh;\n}\n\n"
                        ".page {\n  max-width: 960px;\n  margin: 0 auto;\n  padding: 4rem 1.5rem 6rem;\n}\n\n"
                        ".hero {\n  text-align: center;\n  display: grid;\n  gap: 1.5rem;\n}\n\n"
                        ".badge {\n  display: inline-flex;\n  padding: 0.4rem 0.8rem;\n  border-radius: 999px;\n  background: rgba(59, 130, 246, 0.12);\n  color: #60a5fa;\n  font-weight: 600;\n  letter-spacing: 0.08em;\n  text-transform: uppercase;\n}\n\n"
                        ".cta {\n  display: flex;\n  justify-content: center;\n  gap: 1rem;\n}\n\n"
                        ".button {\n  padding: 0.85rem 1.6rem;\n  border-radius: 0.75rem;\n  font-weight: 600;\n  text-decoration: none;\n  transition: transform 0.2s ease, box-shadow 0.2s ease;\n}\n\n"
                        ".button.primary {\n  background: linear-gradient(135deg, #22d3ee, #3b82f6);\n  color: #020617;\n  box-shadow: 0 18px 45px rgba(56, 189, 248, 0.35);\n}\n\n"
                        ".button.ghost {\n  border: 1px solid rgba(148, 163, 184, 0.25);\n  color: inherit;\n}\n\n"
                        ".panel {\n  margin-top: 4rem;\n  padding: 3rem;\n  border-radius: 1.5rem;\n  background: rgba(15, 23, 42, 0.75);\n  border: 1px solid rgba(148, 163, 184, 0.2);\n}\n\n"
                        ".panel.dark {\n  background: rgba(2, 6, 23, 0.85);\n}\n\n"
                        ".grid {\n  display: grid;\n  gap: 2rem;\n  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));\n}\n\n"
                        "form {\n  display: grid;\n  gap: 0.75rem;\n}\n\n"
                        ".request-form__row {\n  display: flex;\n  gap: 0.75rem;\n}\n\n"
                        ".request-form input {\n  flex: 1;\n  padding: 0.85rem 1rem;\n  border-radius: 0.75rem;\n  border: 1px solid rgba(148, 163, 184, 0.35);\n  background: rgba(15, 23, 42, 0.75);\n  color: inherit;\n}\n\n"
                        ".request-form button {\n  background: linear-gradient(135deg, #22d3ee, #6366f1);\n  border: none;\n  color: #020617;\n  border-radius: 0.75rem;\n  font-weight: 600;\n  padding: 0.85rem 1.4rem;\n}\n\n"
                        ".footer {\n  margin-top: 4rem;\n  text-align: center;\n  color: rgba(226, 232, 240, 0.7);\n}\n"
                    ),
                },
            ),
            BuildStep(
                title="Wire up gentle interactivity",
                description="Add scroll-linked animations and newsletter stub logic.",
                explanation="A touch of motion reinforces that the builder can orchestrate full experiences.",
                files={
                    "public/app.js": (
                        "const form = document.querySelector('.request-form');\n"
                        "if (form) {\n"
                        "  form.addEventListener('submit', (event) => {\n"
                        "    event.preventDefault();\n"
                        "    const email = form.querySelector('input').value;\n"
                        "    const banner = document.createElement('div');\n"
                        "    banner.className = 'toast';\n"
                        "    banner.textContent = `Thanks, ${email}! We'll keep building.`;\n"
                        "    document.body.appendChild(banner);\n"
                        "    setTimeout(() => banner.remove(), 4200);\n"
                        "  });\n"
                        "}\n\n"
                        "const observer = new IntersectionObserver((entries) => {\n"
                        "  entries.forEach((entry) => {\n"
                        "    if (entry.isIntersecting) {\n"
                        "      entry.target.classList.add('reveal');\n"
                        "    }\n"
                        "  });\n"
                        "}, { threshold: 0.2 });\n\n"
                        "document.querySelectorAll('.panel, .hero').forEach((section) => {\n"
                        "  observer.observe(section);\n"
                        "});\n"
                    ),
                },
            ),
        ]
        return BuildPlan(name=name, summary=summary, stack="static-web", steps=steps)

    def _plan_backend(self, prompt: str) -> BuildPlan:
        name = slugify(prompt) or "ai-backend"
        summary = f"FastAPI backend generated for: {prompt.strip()}"
        steps: List[BuildStep] = [
            BuildStep(
                title="Create application skeleton",
                description="Set up FastAPI app instance with health endpoint.",
                explanation="Establishes a predictable entry point for extending the API.",
                files={
                    "app/main.py": (
                        "from fastapi import FastAPI\n\n"
                        "app = FastAPI(title=\"{title}\")\n\n"
                        "@app.get('/health')\n"
                        "async def health() -> dict[str, str]:\n"
                        "    return {'status': 'ok'}\n"
                    ).format(title=prompt.strip().title()),
                },
            ),
            BuildStep(
                title="Model user profile domain",
                description="Define Pydantic models and an in-memory store for quick iteration.",
                explanation="Keeps the generated API stateful without external dependencies.",
                files={
                    "app/schemas.py": (
                        "from __future__ import annotations\n\n"
                        "from pydantic import BaseModel, Field\n\n"
                        "class Profile(BaseModel):\n"
                        "    username: str = Field(..., description='Unique handle for the user')\n"
                        "    display_name: str = Field(..., description='Human readable name')\n"
                        "    bio: str = Field('', description='Profile tagline or summary')\n"
                    ),
                    "app/store.py": (
                        "from __future__ import annotations\n\n"
                        "from typing import Dict\n\n"
                        "from .schemas import Profile\n\n"
                        "class ProfileStore:\n"
                        "    def __init__(self) -> None:\n"
                        "        self._profiles: Dict[str, Profile] = {}\n\n"
                        "    def list(self) -> list[Profile]:\n"
                        "        return list(self._profiles.values())\n\n"
                        "    def get(self, username: str) -> Profile | None:\n"
                        "        return self._profiles.get(username)\n\n"
                        "    def save(self, profile: Profile) -> Profile:\n"
                        "        self._profiles[profile.username] = profile\n"
                        "        return profile\n\n"
                        "    def delete(self, username: str) -> None:\n"
                        "        self._profiles.pop(username, None)\n\n"
                        "store = ProfileStore()\n"
                    ),
                },
            ),
            BuildStep(
                title="Expose CRUD routes",
                description="Implement REST endpoints with validation and error handling.",
                explanation="Demonstrates best practices for designing clean API contracts.",
                files={
                    "app/routes.py": (
                        "from fastapi import APIRouter, HTTPException\n\n"
                        "from .schemas import Profile\n"
                        "from .store import store\n\n"
                        "router = APIRouter(prefix='/profiles', tags=['profiles'])\n\n"
                        "@router.get('/')\n"
                        "async def list_profiles() -> list[Profile]:\n"
                        "    return store.list()\n\n"
                        "@router.post('/', status_code=201)\n"
                        "async def create_profile(profile: Profile) -> Profile:\n"
                        "    if store.get(profile.username):\n"
                        "        raise HTTPException(status_code=409, detail='Profile already exists')\n"
                        "    return store.save(profile)\n\n"
                        "@router.get('/{username}')\n"
                        "async def get_profile(username: str) -> Profile:\n"
                        "    profile = store.get(username)\n"
                        "    if not profile:\n"
                        "        raise HTTPException(status_code=404, detail='Profile not found')\n"
                        "    return profile\n\n"
                        "@router.put('/{username}')\n"
                        "async def update_profile(username: str, payload: Profile) -> Profile:\n"
                        "    existing = store.get(username)\n"
                        "    if not existing:\n"
                        "        raise HTTPException(status_code=404, detail='Profile not found')\n"
                        "    merged = existing.copy(update=payload.model_dump(exclude_unset=True))\n"
                        "    return store.save(merged)\n\n"
                        "@router.delete('/{username}', status_code=204)\n"
                        "async def delete_profile(username: str) -> None:\n"
                        "    store.delete(username)\n"
                    ),
                },
            ),
            BuildStep(
                title="Wire routes and document usage",
                description="Mount router on the app and provide instructions for running.",
                explanation="Completes the project with clear next steps for the developer.",
                files={
                    "app/__init__.py": "from .main import app\n",
                    "README.md": (
                        f"# {prompt.strip().title()} API\n\n"
                        "This FastAPI service manages user profiles with in-memory storage.\n\n"
                        "## Running locally\n\n"
                        "```bash\nuvicorn app.main:app --reload\n```\n\n"
                        "Open <http://localhost:8000/docs> to explore the generated OpenAPI docs.\n"
                    ),
                    "requirements.txt": "fastapi>=0.109\nuvicorn[standard]>=0.26\n",
                },
            ),
        ]
        return BuildPlan(name=name, summary=summary, stack="fastapi", steps=steps)

    def _plan_ml(self, prompt: str) -> BuildPlan:
        name = slugify(prompt) or "ai-ml-project"
        summary = f"Machine learning experiment generated for: {prompt.strip()}"
        steps: List[BuildStep] = [
            BuildStep(
                title="Set up experiment scaffold",
                description="Create project structure with configuration and dependencies.",
                explanation="Organises data, models, and training script for reproducibility.",
                files={
                    "README.md": (
                        f"# {prompt.strip().title()}\n\n"
                        "Generated experiment scaffold for rapid iteration.\n"
                        "\n## Usage\n"
                        "```bash\npython src/train.py\n```\n"
                    ),
                    "pyproject.toml": (
                        "[tool.poetry]\nname = \"{name}\"\nversion = \"0.1.0\"\ndescription = \"Generated ML experiment\"\n"
                        "authors = [\"AI Builder <builder@example.com>\"]\n\n"
                        "[tool.poetry.dependencies]\npython = \"^3.11\"\nnumpy = \"^1.26\"\npandas = \"^2.2\"\nscikit-learn = \"^1.4\"\n"
                    ).format(name=name),
                },
            ),
            BuildStep(
                title="Implement dataset utilities",
                description="Provide data loading and preprocessing helpers.",
                explanation="Keeps experiments tidy with reusable loading routines.",
                files={
                    "src/data.py": (
                        "from __future__ import annotations\n\n"
                        "from pathlib import Path\n\n"
                        "import pandas as pd\n\n"
                        "def load_dataset(path: str | Path) -> pd.DataFrame:\n"
                        "    data_path = Path(path)\n"
                        "    if not data_path.exists():\n"
                        "        raise FileNotFoundError(f'Dataset not found: {data_path}')\n"
                        "    return pd.read_csv(data_path)\n"
                    ),
                },
            ),
            BuildStep(
                title="Draft training loop",
                description="Train a small model with configurable parameters and metrics logging.",
                explanation="Gives an executable baseline that can be iterated upon quickly.",
                files={
                    "src/train.py": (
                        "from __future__ import annotations\n\n"
                        "import argparse\n"
                        "from pathlib import Path\n\n"
                        "import joblib\n"
                        "from sklearn.metrics import classification_report\n"
                        "from sklearn.model_selection import train_test_split\n"
                        "from sklearn.naive_bayes import MultinomialNB\n\n"
                        "from .data import load_dataset\n\n"
                        "def train(dataset: Path, target: str) -> None:\n"
                        "    df = load_dataset(dataset)\n"
                        "    features = df.drop(columns=[target])\n"
                        "    labels = df[target]\n"
                        "    x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)\n"
                        "    model = MultinomialNB()\n"
                        "    model.fit(x_train, y_train)\n"
                        "    predictions = model.predict(x_test)\n"
                        "    print(classification_report(y_test, predictions))\n"
                        "    joblib.dump(model, Path('artifacts') / 'model.joblib')\n\n"
                        "def main() -> None:\n"
                        "    parser = argparse.ArgumentParser(description='{summary}')\n"
                        "    parser.add_argument('--dataset', type=Path, default=Path('data/dataset.csv'))\n"
                        "    parser.add_argument('--target', type=str, default='label')\n"
                        "    args = parser.parse_args()\n"
                        "    Path('artifacts').mkdir(exist_ok=True)\n"
                        "    train(args.dataset, args.target)\n\n"
                        "if __name__ == '__main__':\n"
                        "    main()\n"
                    ).format(summary=summary),
                },
            ),
        ]
        return BuildPlan(name=name, summary=summary, stack="ml-experiment", steps=steps)

    def _plan_script(self, prompt: str) -> BuildPlan:
        name = slugify(prompt) or "ai-builder"
        summary = f"Python automation generated for: {prompt.strip()}"
        steps: List[BuildStep] = [
            BuildStep(
                title="Prepare CLI entry point",
                description="Expose a command-line interface capturing the requested behaviour.",
                explanation="Ensures the generated tool is easy to run locally.",
                files={
                    "src/__init__.py": "",
                    "src/main.py": (
                        "import argparse\n\n"
                        "def run(message: str) -> None:\n"
                        "    print(f'AI Builder executed: {message}')\n\n"
                        "def cli() -> None:\n"
                        "    parser = argparse.ArgumentParser(description='{summary}')\n"
                        "    parser.add_argument('message', help='Instruction to execute')\n"
                        "    args = parser.parse_args()\n"
                        "    run(args.message)\n\n"
                        "if __name__ == '__main__':\n"
                        "    cli()\n"
                    ).format(summary=summary),
                },
            ),
            BuildStep(
                title="Document usage",
                description="Provide README with installation and execution instructions.",
                explanation="Gives future iterations context about the generated automation.",
                files={
                    "README.md": (
                        f"# {prompt.strip().title()}\n\n"
                        "This utility was generated by the AI Builder environment.\n"
                        "\n## Usage\n"
                        "```bash\npython -m src.main 'Your message here'\n```\n"
                    ),
                },
            ),
            BuildStep(
                title="Define project metadata",
                description="Include dependencies and tooling configuration.",
                explanation="Keeps the scaffold ready for packaging or further automation.",
                files={
                    "pyproject.toml": (
                        "[project]\nname = \"{name}\"\nversion = \"0.1.0\"\ndescription = \"Automation generated by AI Builder\"\n"
                        "authors = [{{name = 'AI Builder', email = 'builder@example.com'}}]\n\n"
                        "[project.scripts]\n{name} = \"src.main:cli\"\n"
                    ).format(name=name),
                },
            ),
        ]
        return BuildPlan(name=name, summary=summary, stack="python-tool", steps=steps)

    # ------------------------------------------------------------------
    # execution
    # ------------------------------------------------------------------
    async def run_build(self, session_id: str) -> None:
        session = build_stream.get_session(session_id)
        if session is None:
            return
        prompt = session.prompt.strip()
        build_stream.publish(session_id, {"type": "status", "stage": "understanding", "message": "Understanding request"})
        await asyncio.sleep(0.05)
        try:
            plan = self.create_plan(prompt)
            candidate = project_manager.ensure_unique_name(plan.name)
            session.project_name = candidate
            project_manager.initialize_project(candidate, plan.summary, prompt, plan.stack)
            project_manager.update_manifest(
                candidate,
                summary=plan.summary,
                prompt=prompt,
                stack=plan.stack,
                plan=plan.to_dict(),
            )
            project_manager.append_history(candidate, {"type": "plan", "summary": plan.summary})
            build_stream.publish(
                session_id,
                {
                    "type": "plan",
                    "plan": plan.to_dict(),
                    "project": candidate,
                },
            )
            context = ExecutionContext(session_id=session_id, project_name=candidate)

            for index, step in enumerate(plan.steps, start=1):
                build_stream.publish(
                    session_id,
                    {
                        "type": "step",
                        "status": "start",
                        "index": index,
                        "title": step.title,
                        "description": step.description,
                        "explanation": step.explanation,
                    },
                )
                project_manager.append_history(
                    candidate,
                    {
                        "type": "step-start",
                        "index": index,
                        "title": step.title,
                        "description": step.description,
                    },
                )

                async def on_write(path: str, content: str) -> None:
                    build_stream.publish(
                        session_id,
                        {
                            "type": "file",
                            "path": path,
                            "content": content,
                            "step": index,
                        },
                    )
                    project_manager.append_history(
                        candidate,
                        {
                            "type": "file",
                            "step": index,
                            "path": path,
                        },
                    )

                await code_executor.apply_files(context, step.files, on_write=on_write)

                build_stream.publish(
                    session_id,
                    {
                        "type": "step",
                        "status": "complete",
                        "index": index,
                        "title": step.title,
                    },
                )
                project_manager.append_history(
                    candidate,
                    {
                        "type": "step-complete",
                        "index": index,
                        "title": step.title,
                    },
                )

            project_manager.append_history(
                candidate,
                {"type": "complete", "message": "Build finished"},
            )
            build_stream.publish(
                session_id,
                {
                    "type": "complete",
                    "project": candidate,
                    "summary": plan.summary,
                },
            )
        except Exception as exc:  # pragma: no cover - defensive
            if session.project_name:
                project_manager.append_history(
                    session.project_name,
                    {"type": "error", "message": str(exc)},
                )
            build_stream.publish(
                session_id,
                {
                    "type": "error",
                    "message": str(exc),
                },
            )
        finally:
            build_stream.close(session_id)


ai_controller = AIController()
